### ISSUE TITLE
Missing functions in cudart spec?

### ISSUE THREAD

**Issue by vancemiller** [utcs-scea/ava#87]
Remoting vector_add benchmark from Cuda 10.1 samples with AvA's cudart spec seems to have a missing function.

```
symbol cudaGetErrorName version libcudart.so.10.1 not defined in file libcudart.so.10.1 with link time reference
```

I tried to add this function to the cudart_opt.c spec and recompile:
```
__host__ __cudart_builtin__ const char* CUDARTAPI
cudaGetErrorName(cudaError_t error)
{
    const char *ret = ava_execute();
    ava_return_value {
        ava_out; ava_buffer(strlen(ret) + 1);
        ava_lifetime_static;
    }
}
```
same error

**Comment by vancemiller** [comment]
Is there a cudart spec that doesn't dump functions? The dumping makes it hard to run arbitrary applications without seeing them beforehand. It seems like the cudart_dump and cudart_opt are designed for tensorflow, but isn't that already covered by the tensorflow specs? Can these be simplified?

**Comment by vancemiller** [comment]
> 
> 
> Remoting vector_add benchmark from Cuda 10.1 samples with AvA's cudart spec seems to have a missing function.
> 
> ```
> symbol cudaGetErrorName version libcudart.so.10.1 not defined in file libcudart.so.10.1 with link time reference
> ```
> 
> I tried to add this function to the cudart_opt.c spec and recompile:
> 
> ```
> __host__ __cudart_builtin__ const char* CUDARTAPI
> cudaGetErrorName(cudaError_t error)
> {
>     const char *ret = ava_execute();
>     ava_return_value {
>         ava_out; ava_buffer(strlen(ret) + 1);
>         ava_lifetime_static;
>     }
> }
> ```
> 
> same error

I needed to add this to cudart.c instead of cudart_opt.c. What's the difference between these?

Now:

```
/data/NVIDIA_CUDA-10.1_Samples/0_Simple/vector    Add/vectorAdd: relocation error: /data/NVIDIA_    CUDA-10.1_Samples/0_Simple/vectorAdd/vectorAdd    : symbol __cudaRegisterFatBinaryEnd version li    bcudart.so.10.1 not defined in file libcudart.    so.10.1 with link time reference
```

This is already defined in cudart.c, but it's wrapped with `ava_*replacement`.

**Comment by yuhc** [comment]
There is one and I think it's `cudart/cudart.c` that doesn't need to dump fatbins.
Actually all dump specs can be used standalone with small changes. The trick is to let guestlib parses fatbins and *sends* fatbins to worker. For opt specs, they *load* fatbins from previous dumped fatbin files instead of *receving* them from guestlib.

All `*_opt.c` specs are paired with corresponding *_dump.c* specs. They are targeted for saving the fatbin loading time.
As mentioned, `cudart.c` is a standalone spec without dumping required (it still generates fatbin dumps because we need to parse arguments' information with cuobjdump).

For the `__cudaRegisterFatBinaryEnd ` error, the annotation should be:
```
EXPORTED void CUDARTAPI __cudaRegisterFatBinaryEnd
...
```
If any annotation doesn't work, just copy the correct one from `onnx_opt.c`.
